module.exports = {  
   "message":"accurate",
   "cod":"200",
   "count":10,
   "list":[  
      {  
         "id":4591655,
         "name":"Pleasant View (historical)",
         "coord":{  
            "lon":-79.965622,
            "lat":34.121269
         },
         "main":{  
            "temp":294.484,
            "temp_min":294.484,
            "temp_max":294.484,
            "pressure":1026.35,
            "sea_level":1030.63,
            "grnd_level":1026.35,
            "humidity":60
         },
         "dt":1456074132,
         "wind":{  
            "speed":6.56,
            "deg":232.5
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":92
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ]
      },
      {  
         "id":4598692,
         "name":"Timmonsville",
         "coord":{  
            "lon":-79.939789,
            "lat":34.13488
         },
         "main":{  
            "temp":294.484,
            "temp_min":294.484,
            "temp_max":294.484,
            "pressure":1026.35,
            "sea_level":1030.63,
            "grnd_level":1026.35,
            "humidity":60
         },
         "dt":1456074082,
         "wind":{  
            "speed":6.56,
            "deg":232.5
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":92
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ]
      },
      {  
         "id":4599503,
         "name":"Vaughans Crossroads",
         "coord":{  
            "lon":-80.102287,
            "lat":34.208771
         },
         "main":{  
            "temp":294.409,
            "temp_min":294.409,
            "temp_max":294.409,
            "pressure":1021.49,
            "sea_level":1030.3,
            "grnd_level":1021.49,
            "humidity":62
         },
         "dt":1456074132,
         "wind":{  
            "speed":6.21,
            "deg":233.5
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":68
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ]
      },
      {  
         "id":4578737,
         "name":"Florence",
         "coord":{  
            "lon":-79.762558,
            "lat":34.195431
         },
         "main":{  
            "temp":294.484,
            "temp_min":294.484,
            "temp_max":294.484,
            "pressure":1026.35,
            "sea_level":1030.63,
            "grnd_level":1026.35,
            "humidity":60
         },
         "dt":1456073653,
         "wind":{  
            "speed":6.56,
            "deg":232.5
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":92
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ]
      },
      {  
         "id":4584322,
         "name":"Lake City",
         "coord":{  
            "lon":-79.755348,
            "lat":33.870998
         },
         "main":{  
            "temp":292.87,
            "pressure":1018,
            "humidity":68,
            "temp_min":291.15,
            "temp_max":294.15
         },
         "dt":1456072500,
         "wind":{  
            "speed":4.6,
            "deg":220
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":1
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ]
      },
      {  
         "id":4577347,
         "name":"East Sumter",
         "coord":{  
            "lon":-80.296188,
            "lat":33.925442
         },
         "main":{  
            "temp":296.309,
            "temp_min":296.309,
            "temp_max":296.309,
            "pressure":1026.68,
            "sea_level":1031.19,
            "grnd_level":1026.68,
            "humidity":48
         },
         "dt":1456073708,
         "wind":{  
            "speed":6.51,
            "deg":232
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":44
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ]
      },
      {  
         "id":4578745,
         "name":"Florence County",
         "coord":{  
            "lon":-79.666451,
            "lat":34.050159
         },
         "main":{  
            "temp":292.83,
            "pressure":1018,
            "humidity":68,
            "temp_min":291.15,
            "temp_max":294.15
         },
         "dt":1456072500,
         "wind":{  
            "speed":4.6,
            "deg":220
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":1
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"Sky is Clear",
               "icon":"01d"
            }
         ]
      },
      {  
         "id":4571470,
         "name":"Bishopville",
         "coord":{  
            "lon":-80.248413,
            "lat":34.218208
         },
         "main":{  
            "temp":294.409,
            "temp_min":294.409,
            "temp_max":294.409,
            "pressure":1021.49,
            "sea_level":1030.3,
            "grnd_level":1021.49,
            "humidity":62
         },
         "dt":1456074133,
         "wind":{  
            "speed":6.21,
            "deg":233.5
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":68
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ]
      },
      {  
         "id":4576319,
         "name":"Darlington",
         "coord":{  
            "lon":-79.876167,
            "lat":34.299881
         },
         "main":{  
            "temp":294.484,
            "temp_min":294.484,
            "temp_max":294.484,
            "pressure":1026.35,
            "sea_level":1030.63,
            "grnd_level":1026.35,
            "humidity":60
         },
         "dt":1456074155,
         "wind":{  
            "speed":6.56,
            "deg":232.5
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":92
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ]
      },
      {  
         "id":4592283,
         "name":"Quinns Crossroad",
         "coord":{  
            "lon":-80.345078,
            "lat":33.989319
         },
         "main":{  
            "temp":296.309,
            "temp_min":296.309,
            "temp_max":296.309,
            "pressure":1026.68,
            "sea_level":1031.19,
            "grnd_level":1026.68,
            "humidity":48
         },
         "dt":1456074133,
         "wind":{  
            "speed":6.51,
            "deg":232
         },
         "sys":{  
            "country":""
         },
         "clouds":{  
            "all":44
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ]
      }
   ]
}